<?php

return array(
    array (
        "name" => "12 labels",
        "width" => 70,
        "height" => 67.7,
        "arround" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 13.1,
        "marginBottom" => 13.1,
        "arroundCount" => 4,
        "acrossCount" => 3,
        "paperId" => 1,
        "default" => 0,
    ),
    array (
        "name" => "12 labels",
        "width" => 105,
        "height" => 48,
        "arround" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 4.5,
        "marginBottom" => 4.5,
        "arroundCount" => 6,
        "acrossCount" => 2,
        "paperId" => 1,
        "default" => 0,
    ),
    array (
        "name" => "14 labels",
        "width" => 105,
        "height" => 41,
        "arround" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 5,
        "marginBottom" => 5,
        "arroundCount" => 7,
        "acrossCount" => 2,
        "paperId" => 1,
        "default" => 0,
    ),
    array (
        "name" => "14 labels",
        "width" => 105,
        "height" => 42.4,
        "arround" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 0.1,
        "marginBottom" => 0.1,
        "arroundCount" => 7,
        "acrossCount" => 2,
        "paperId" => 1,
        "default" => 0,
    ),
    array (
        "name" => "14 labels",
       "width" => 105,
       "height" => 38,
       "arround" => 0,
       "across" => 0,
       "marginLeft" => 0,
       "marginRight" => 0,
       "marginTop" => 15.5,
       "marginBottom" => 15.5,
       "arroundCount" => 7,
       "acrossCount" => 2,
       "paperId" => 1,
        "default" => 0,
    ),
    array (
        "name" => "16 labels",
       "width" => 105,
       "height" => 35,
       "arround" => 0,
       "across" => 0,
       "marginLeft" => 0,
       "marginRight" => 0,
       "marginTop" => 8.5,
       "marginBottom" => 8.5,
       "arroundCount" => 8,
       "acrossCount" => 2,
       "paperId" => 1,
        "default" => 0,
    ),
    array (
        "name" => "16 labels",
       "width" => 105,
       "height" => 37,
       "arround" => 0,
       "across" => 0,
       "marginLeft" => 0,
       "marginRight" => 0,
       "marginTop" => 0.5,
       "marginBottom" => 0.5,
       "arroundCount" => 8,
       "acrossCount" => 2,
       "paperId" => 1,
        "default" => 0,
    ),
    array (
        "name" => "21 labels",
        "width" => 70,
        "height" => 42.41,
        "arround" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 0.1,
        "marginBottom" => 0.1,
        "arroundCount" => 7,
        "acrossCount" => 3,
        "paperId" => 1,
        "default" => 0,
    ),
    array (
        "name" => "24 labels",
        "width" => 70,
        "height" => 37,
        "arround" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 0.5,
        "marginBottom" => 0.5,
        "arroundCount" => 8,
        "acrossCount" => 3,
        "paperId" => 1,
        "default" => 0,
    ),
    array (
        "name" => "40 labels",
        "width" => 52.5,
        "height" => 29.6,
        "arround" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 0.5,
        "marginBottom" => 0.5,
        "arroundCount" => 10,
        "acrossCount" => 4,
        "paperId" => 1,
        "default" => 0,
    ),
    array (
        "name" => "56 labels",
        "width" => 52.5,
        "height" => 21.2,
        "arround" => 0,
        "across" => 0,
        "marginLeft" => 0,
        "marginRight" => 0,
        "marginTop" => 0.1,
        "marginBottom" => 0.1,
        "arroundCount" => 14,
        "acrossCount" => 4,
        "paperId" => 1,
        "default" => 0,
    ),
    array (
        "name" => "65 labels",
        "width" => 38.1,
        "height" => 21.2,
        "arround" => 0,
        "across" => 2,
        "marginLeft" => 5.7,
        "marginRight" => 5.8,
        "marginTop" => 10.7,
        "marginBottom" => 10.7,
        "arroundCount" => 13,
        "acrossCount" => 5,
        "paperId" => 1,
        "default" => 0,
    ),
    array (
        "name" => "44 labels",
        "width" => 48.5,
        "height" => 25.4,
        "arround" => 0,
        "across" => 0,
        "marginLeft" => 8,
        "marginRight" => 8,
        "marginTop" => 8.8,
        "marginBottom" => 8.8,
        "arroundCount" => 11,
        "acrossCount" => 4,
        "paperId" => 1,
        "default" => 0,
    ),
    array (
        "name" => "120 labels",
        "width" => 22,
        "height" => 16,
        "arround" => 2,
        "across" => 2,
        "marginLeft" => 10,
        "marginRight" => 10,
        "marginTop" => 14.5,
        "marginBottom" => 14.5,
        "arroundCount" => 15,
        "acrossCount" => 8,
        "paperId" => 1,
        "default" => 0,
    ),
    array (
        "name" => "189 labels",
        "width" => 25.4,
        "height" => 10,
        "arround" => 0,
        "across" => 2.5,
        "marginLeft" => 8.6,
        "marginRight" => 8.6,
        "marginTop" => 13.5,
        "marginBottom" => 13.5,
        "arroundCount" => 27,
        "acrossCount" => 7,
        "paperId" => 1,
        "default" => 0,
    ),
    array (
        "name" => "230 labels",
        "width" => 14,
        "height" => 9,
        "arround" => 3,
        "across" => 5,
        "marginLeft" => 12.5,
        "marginRight" => 12.5,
        "marginTop" => 12,
        "marginBottom" => 12,
        "arroundCount" => 23,
        "acrossCount" => 10,
        "paperId" => 1,
        "default" => 0,
    ),
    array (
        "name" => "324 labels",
        "width" => 17,
        "height" => 6,
        "arround" => 2,
        "across" => 3,
        "marginLeft" => 16.5,
        "marginRight" => 16.5,
        "marginTop" => 5.5,
        "marginBottom" => 5.5,
        "arroundCount" => 36,
        "acrossCount" => 9,
        "paperId" => 1,
        "default" => 0,
    ),
    array (
        "name" => "6 labels",
        "width" => 95.25,
        "height" => 76.2,
        "arround" => 9.52,
        "across" => 6.35,
        "marginLeft" => 9.52,
        "marginRight" => 9.52,
        "marginTop" => 15.88,
        "marginBottom" => 15.88,
        "arroundCount" => 3,
        "acrossCount" =>  2,
        "paperId" => 2,
        "default" => 0,
    ),
    
);

