<?php

return array(
    array(
        'id' => 1,
        'name' => 'A4 (210 × 297 mm)',
        'width' => 210,
        'height' => 297,
        'default' => 1,
        'uol' => 'mm',
        'is_editable' => 1,
    ),
    array(
        'id' => 2,
        'name' => 'Letter (8.5 × 11 in)',
        'width' => 8.5,
        'height' => 11,
        'default' => 1,
        'uol' => 'in',
        'is_editable' => 1,
    ),
    array(
        'id' => 3,
        'name' => 'P4 (215 × 280 mm)',
        'width' => 215,
        'height' => 280,
        'default' => 1,
        'uol' => 'mm',
        'is_editable' => 1,
    ),
    array(
        'id' => 4,
        'name' => 'Roll Thermal Printer',
        'width' => 70,
        'height' => 44,
        'default' => 1,
        'uol' => 'mm',
        'is_editable' => 1,
    ),
    array(
        'id' => 5,
        'name' => 'future-reserved-paper-format',
        'width' => 210,
        'height' => 297,
        'default' => 1,
        'uol' => 'mm',
        'is_editable' => 0,
    ),
    array(
        'id' => 6,
        'name' => 'future-reserved-paper-format',
        'width' => 210,
        'height' => 297,
        'default' => 1,
        'uol' => 'mm',
        'is_editable' => 0,
    ),
    array(
        'id' => 7,
        'name' => 'future-reserved-paper-format',
        'width' => 210,
        'height' => 297,
        'default' => 1,
        'uol' => 'mm',
        'is_editable' => 0,
    ),
    array(
        'id' => 8,
        'name' => 'future-reserved-paper-format',
        'width' => 210,
        'height' => 297,
        'default' => 1,
        'uol' => 'mm',
        'is_editable' => 0,
    ),
    array(
        'id' => 9,
        'name' => 'future-reserved-paper-format',
        'width' => 210,
        'height' => 297,
        'default' => 1,
        'uol' => 'mm',
        'is_editable' => 0,
    ),
);
