<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6ef396a4dc448dde7e07aff6fe5d6eda
{
    public static $files = array (
        '205fc52e602d8f61b95a211596d32fbf' => __DIR__ . '/..' . '/tcpdf_barcodes_1d.php',
    );

    public static $prefixLengthsPsr4 = array (
        'U' => 
        array (
            'UkrSolution\\WpBarcodesGenerator\\' => 32,
        ),
        'M' => 
        array (
            'Milon\\Barcode\\' => 14,
            'Melgrati\\CodeValidator\\' => 23,
        ),
        'K' => 
        array (
            'Kreativekorp\\' => 13,
        ),
        'C' => 
        array (
            'Com\\Tecnick\\Color\\' => 18,
            'Com\\Tecnick\\Barcode\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'UkrSolution\\WpBarcodesGenerator\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
        'Milon\\Barcode\\' => 
        array (
            0 => __DIR__ . '/..' . '/barcode_generator',
        ),
        'Melgrati\\CodeValidator\\' => 
        array (
            0 => __DIR__ . '/..' . '/barcode_validator',
        ),
        'Kreativekorp\\' => 
        array (
            0 => __DIR__ . '/..' . '/kreativekorp',
        ),
        'Com\\Tecnick\\Color\\' => 
        array (
            0 => __DIR__ . '/..' . '/tecnickcom/tc-lib-color',
            1 => __DIR__ . '/..' . '/tecnickcom/tc-lib-color/src',
        ),
        'Com\\Tecnick\\Barcode\\' => 
        array (
            0 => __DIR__ . '/..' . '/tecnickcom/tc-lib-barcode',
            1 => __DIR__ . '/..' . '/tecnickcom/tc-lib-barcode/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6ef396a4dc448dde7e07aff6fe5d6eda::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6ef396a4dc448dde7e07aff6fe5d6eda::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
