<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '205fc52e602d8f61b95a211596d32fbf' => $vendorDir . '/tcpdf_barcodes_1d.php',
);
