<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'UkrSolution\\WpBarcodesGenerator\\' => array($baseDir . '/class'),
    'Milon\\Barcode\\' => array($vendorDir . '/barcode_generator'),
    'Melgrati\\CodeValidator\\' => array($vendorDir . '/barcode_validator'),
    'Kreativekorp\\' => array($vendorDir . '/kreativekorp'),
    'Com\\Tecnick\\Color\\' => array($vendorDir . '/tecnickcom/tc-lib-color', $vendorDir . '/tecnickcom/tc-lib-color/src'),
    'Com\\Tecnick\\Barcode\\' => array($vendorDir . '/tecnickcom/tc-lib-barcode', $vendorDir . '/tecnickcom/tc-lib-barcode/src'),
);
